/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GadgetRouteImport } from './routes/gadget'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AllStocksRouteImport } from './routes/all-stocks'
import { Route as IndexRouteImport } from './routes/index'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GadgetRoute = GadgetRouteImport.update({
  id: '/gadget',
  path: '/gadget',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AllStocksRoute = AllStocksRouteImport.update({
  id: '/all-stocks',
  path: '/all-stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-stocks': typeof AllStocksRoute
  '/customers': typeof CustomersRoute
  '/gadget': typeof GadgetRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/search': typeof SearchRoute
  '/warranty': typeof WarrantyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-stocks': typeof AllStocksRoute
  '/customers': typeof CustomersRoute
  '/gadget': typeof GadgetRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/search': typeof SearchRoute
  '/warranty': typeof WarrantyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-stocks': typeof AllStocksRoute
  '/customers': typeof CustomersRoute
  '/gadget': typeof GadgetRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/search': typeof SearchRoute
  '/warranty': typeof WarrantyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-stocks'
    | '/customers'
    | '/gadget'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/sales'
    | '/search'
    | '/warranty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-stocks'
    | '/customers'
    | '/gadget'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/sales'
    | '/search'
    | '/warranty'
  id:
    | '__root__'
    | '/'
    | '/all-stocks'
    | '/customers'
    | '/gadget'
    | '/inventory'
    | '/login'
    | '/reports'
    | '/sales'
    | '/search'
    | '/warranty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllStocksRoute: typeof AllStocksRoute
  CustomersRoute: typeof CustomersRoute
  GadgetRoute: typeof GadgetRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SearchRoute: typeof SearchRoute
  WarrantyRoute: typeof WarrantyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gadget': {
      id: '/gadget'
      path: '/gadget'
      fullPath: '/gadget'
      preLoaderRoute: typeof GadgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-stocks': {
      id: '/all-stocks'
      path: '/all-stocks'
      fullPath: '/all-stocks'
      preLoaderRoute: typeof AllStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllStocksRoute: AllStocksRoute,
  CustomersRoute: CustomersRoute,
  GadgetRoute: GadgetRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SearchRoute: SearchRoute,
  WarrantyRoute: WarrantyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
